# Generated by Django 3.1.7 on 2021-03-11 10:29

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartners',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the Channel Partner', max_length=255, verbose_name='Channel Partner')),
                ('code', models.CharField(help_text='Will beprefixed with lmsId to generate loanId', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Channel Partner',
                'verbose_name_plural': 'Channel Partners',
            },
        ),
        migrations.CreateModel(
            name='LoanManagementSystem',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='API Base URL')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('jwt_obtain', models.URLField(blank=True, max_length=255, null=True, verbose_name='JWT Obtain URL')),
                ('jwt_refresh', models.URLField(blank=True, max_length=255, null=True, verbose_name='JWT Refresh URL')),
                ('name', models.CharField(help_text='Name of Loan Management System', max_length=255, verbose_name='LMS')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='LMS Code')),
            ],
            options={
                'verbose_name': 'LMS',
                'verbose_name_plural': 'LMS',
            },
        ),
        migrations.CreateModel(
            name='LoanManagementSystemAPI',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the API', max_length=255, verbose_name='API Name')),
                ('host', models.CharField(max_length=255, verbose_name='API Path')),
                ('query_params', models.JSONField(blank=True, default=dict, null=True)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE')])),
                ('auth_scheme', models.PositiveSmallIntegerField(choices=[(1, 'API Key'), (2, 'Bearer Token')])),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data', models.ManyToManyField(through='borrowers.LoanApplicationData', to='borrowers.LoanApplication')),
                ('lms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.loanmanagementsystem', verbose_name='LMS')),
            ],
            options={
                'verbose_name': 'LMS API',
                'verbose_name_plural': 'LMS APIs',
            },
        ),
    ]
