# Generated by Django 3.1.7 on 2021-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanmanagementsystemapi',
            options={'verbose_name': 'LMS API', 'verbose_name_plural': 'LMS API'},
        ),
        migrations.RenameField(
            model_name='loanmanagementsystemapi',
            old_name='host',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='loanmanagementsystemapi',
            name='query_params',
        ),
        migrations.AddField(
            model_name='loanmanagementsystemapi',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Query Parameters'),
        ),
        migrations.AlterField(
            model_name='loanmanagementsystemapi',
            name='auth_scheme',
            field=models.PositiveSmallIntegerField(choices=[(1, 'API Key'), (2, 'Bearer Token')], verbose_name='Auth Scheme'),
        ),
        migrations.AlterField(
            model_name='loanmanagementsystemapi',
            name='body',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Body'),
        ),
    ]
