# Generated by Django 3.1.8 on 2021-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20210507_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmanagementsystemapi',
            name='iterable',
            field=models.BooleanField(blank=True, default=False, help_text='Yes if the API is going to be called                             multiple times then also configure Iterable Data                             Settings', null=True, verbose_name='API Iterable'),
        ),
        migrations.AlterField(
            model_name='loanmanagementsystemapi',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='platformserviceapi',
            name='iterable',
            field=models.BooleanField(blank=True, default=False, help_text='Yes if the API is going to be called                             multiple times then also configure Iterable Data                             Settings', null=True, verbose_name='API Iterable'),
        ),
        migrations.AlterField(
            model_name='platformserviceapi',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
    ]
