# Generated by Django 3.1.7 on 2021-03-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20210311_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmanagementsystemapi',
            name='headers',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Headers'),
        ),
        migrations.AlterField(
            model_name='loanmanagementsystemapi',
            name='auth_scheme',
            field=models.CharField(choices=[('Token', 'Token'), ('Bearer', 'Bearer'), ('Basic', 'Basic')], max_length=10, verbose_name='Auth Scheme'),
        ),
        migrations.AlterField(
            model_name='loanmanagementsystemapi',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('PUT', 'PUT'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, verbose_name='HTTP Method'),
        ),
    ]
