# Generated by Django 3.1.7 on 2021-03-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_auto_20210311_1628'),
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendersystemapi',
            options={'verbose_name': 'Lender API', 'verbose_name_plural': 'Lenders API'},
        ),
        migrations.AlterModelOptions(
            name='loandata',
            options={'verbose_name': 'Loan Data', 'verbose_name_plural': 'Loans Data'},
        ),
        migrations.RenameField(
            model_name='lendersystemapi',
            old_name='host',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='lendersystemapi',
            name='query_params',
        ),
        migrations.AddField(
            model_name='lendersystemapi',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Query Parameters'),
        ),
        migrations.AlterField(
            model_name='lendersystemapi',
            name='auth_scheme',
            field=models.PositiveSmallIntegerField(choices=[(1, 'API Key'), (2, 'Bearer Token')], verbose_name='Auth Scheme'),
        ),
        migrations.AlterField(
            model_name='lendersystemapi',
            name='body',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Body'),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.loanapplication', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='lender_api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lenders.lendersystemapi', verbose_name='Lender API'),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='request',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='response_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
