# Generated by Django 3.1.8 on 2021-05-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_auto_20210519_1508'),
        ('lenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendersystemapi',
            name='process_status_logic',
            field=models.TextField(blank=True, null=True, verbose_name='Process Status Logic'),
        ),
        migrations.AddField(
            model_name='loandata',
            name='process_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Logic'),
        ),
        migrations.AddField(
            model_name='loandata',
            name='response_time',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lendersystemapi',
            name='iterable',
            field=models.BooleanField(blank=True, default=False, help_text='Yes if the API is going to be called                             multiple times then also configure Iterable Data                             Settings', null=True, verbose_name='Iterable'),
        ),
        migrations.AlterField(
            model_name='lendersystemapi',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.loanapplication', verbose_name='LoanID'),
        ),
        migrations.AlterField(
            model_name='loandata',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.loanapplication', verbose_name='LoanID'),
        ),
    ]
