# Generated by Django 3.1.7 on 2021-03-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0002_auto_20210311_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendersystemapi',
            name='auth_scheme',
            field=models.CharField(choices=[('Bearer', 'Bearer'), ('Basic', 'Basic'), ('Token', 'Token')], max_length=10, verbose_name='Auth Scheme'),
        ),
        migrations.AlterField(
            model_name='lendersystemapi',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, verbose_name='HTTP Method'),
        ),
    ]
