version: "3"
volumes:
  data:
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=services
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  django:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    tty: true
    command: python manage.py runserver --insecure 0:8000
    volumes:
      - ./app:/src/app
    ports:
      - "8000:8000"
