apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: production
  name: mf-services-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=6000
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz/
spec:
  tls:
  - hosts:
    - services.prod.mayafin.in
  rules:
  - host: services.prod.mayafin.in
    http:
      paths:
      - path: /favicon.ico
        backend:
          serviceName: mf-services-svc
          servicePort: 8001
      - path: /robots.txt
        backend:
          serviceName: mf-services-svc
          servicePort: 8001
      - path: /static/
        backend:
          serviceName: mf-services-svc
          servicePort: 8001
      - path: /media/
        backend:
          serviceName: mf-services-svc
          servicePort: 8001
      - path: /
        backend:
          serviceName: mf-services-svc
          servicePort: 8000

