apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: django-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
