apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: django-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
