# Generated by Django 3.1.7 on 2021-03-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationdata',
            name='lms_api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.loanmanagementsystemapi', verbose_name='LMS API'),
        ),
        migrations.AddField(
            model_name='loanapplicationdata',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.loanapplication', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.channelpartners', verbose_name='Channel Partner'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='lms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforms.loanmanagementsystem', verbose_name='LMS'),
        ),
        migrations.AlterUniqueTogether(
            name='loanapplication',
            unique_together={('lms', 'lmsid')},
        ),
    ]
