# Generated by Django 3.1.7 on 2021-03-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_auto_20210311_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplicationdata',
            options={'verbose_name': 'Application Data', 'verbose_name_plural': 'Applications Data'},
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='request',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='response_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
