# Generated by Django 3.1.8 on 2021-05-19 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_auto_20210318_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationdata',
            name='process_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Logic'),
        ),
        migrations.AddField(
            model_name='loanapplicationdata',
            name='response_time',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='lmsid',
            field=models.CharField(help_text='Loan Application Reference No. at LMS', max_length=255, null=True, verbose_name='LoanID'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrowers.loanapplication', verbose_name='LoanID'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='response_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
