# Generated by Django 3.1.8 on 2021-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0003_auto_20210507_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationdata',
            name='response_time',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='process_status',
            field=models.BooleanField(default=True, verbose_name='Logic'),
        ),
    ]
